In [1]:
import pandas as pd

df =pd.read_csv('./assignments/billboard.csv')
df

,year,artist,track,time,date.entered,wk1,wk2,wk3,wk4,wk5,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,87,82.0,72.0,77.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,91,87.0,92.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,81,70.0,68.0,67.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,3 Doors Down,Loser,4:24,2000-10-21,76,76.0,72.0,69.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,57,34.0,25.0,17.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,86,83.0,77.0,74.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,85,83.0,83.0,82.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,95,94.0,91.0,85.0,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,matchbox twenty,Bent,4:12,2000-04-29,60,37.0,29.0,24.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df = df.melt(id_vars=['year' ,'artist', 'track' ,'time' ,'date.entered'], var_name='week', value_name='rank')
df = df.dropna()
df

,year,artist,track,time,date.entered,week,rank
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...
19716,2000,Creed,Higher,5:16,1999-09-11,wk63,50.0
19833,2000,Lonestar,Amazed,4:25,1999-06-05,wk63,45.0
20033,2000,Creed,Higher,5:16,1999-09-11,wk64,50.0
20150,2000,Lonestar,Amazed,4:25,1999-06-05,wk64,50.0
20350,2000,Creed,Higher,5:16,1999-09-11,wk65,49.0

In [3]:
df = df.reset_index()
df

,index,year,artist,track,time,date.entered,week,rank
0,0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...,...
5302,19716,2000,Creed,Higher,5:16,1999-09-11,wk63,50.0
5303,19833,2000,Lonestar,Amazed,4:25,1999-06-05,wk63,45.0
5304,20033,2000,Creed,Higher,5:16,1999-09-11,wk64,50.0
5305,20150,2000,Lonestar,Amazed,4:25,1999-06-05,wk64,50.0
5306,20350,2000,Creed,Higher,5:16,1999-09-11,wk65,49.0

In [4]:
da = []
for i in range(0,5307):
    j = df['week'][i][2:]
    da.append(j)
da

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 ...]

In [5]:
df['week'] = da
df

,index,year,artist,track,time,date.entered,week,rank
0,0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
1,1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,1,91.0
2,2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,1,81.0
3,3,2000,3 Doors Down,Loser,4:24,2000-10-21,1,76.0
4,4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,1,57.0
...,...,...,...,...,...,...,...,...
5302,19716,2000,Creed,Higher,5:16,1999-09-11,63,50.0
5303,19833,2000,Lonestar,Amazed,4:25,1999-06-05,63,45.0
5304,20033,2000,Creed,Higher,5:16,1999-09-11,64,50.0
5305,20150,2000,Lonestar,Amazed,4:25,1999-06-05,64,50.0
5306,20350,2000,Creed,Higher,5:16,1999-09-11,65,49.0

In [6]:
df.sample(50)

,index,year,artist,track,time,date.entered,week,rank
113,113,2000,"Gray, Macy",I Try,3:52,2000-02-19,1,68.0
3278,3781,2000,"Tritt, Travis",Best Of Intentions,4:15,2000-08-19,12,31.0
222,222,2000,Nelly,(Hot S**t) Country G...,4:17,2000-04-29,1,100.0
572,577,2000,"Simpson, Jessica",I Think I'm In Love ...,3:32,2000-07-01,2,52.0
2868,3212,2000,"Braxton, Toni",Just Be A Man About ...,4:10,2000-07-29,11,50.0
600,605,2000,"Thomas, Carl",I Wish,3:50,2000-03-25,2,64.0
3374,3927,2000,Hoku,Another Dumb Blonde,3:47,2000-02-19,13,80.0
650,656,2000,BBMak,Back Here,3:35,2000-04-29,3,60.0
3227,3708,2000,Nas,You Owe Me,3:51,2000-03-25,12,82.0
3536,4167,2000,Brooks & Dunn,You'll Always Be Lov...,2:58,2000-06-10,14,55.0
204,204,2000,"McKnight, Brian",Stay Or Let It Go,4:32,2000-02-26,1,95.0
1556,1618,2000,Black Rob,Whoa!,4:04,2000-03-04,6,46.0
3642,4338,2000,Mystikal,Shake Ya Ass,4:46,2000-08-12,14,13.0
2575,2834,2000,"Vassar, Phil",Carlene,4:07,2000-03-04,9,45.0
2022,2152,2000,Ruff Endz,No More,3:56,2000-07-01,7,12.0
3047,3455,2000,Third Eye Blind,Deep Inside Of You,4:10,2000-09-02,11,95.0
5063,8712,2000,"Jordan, Montell",Get It On.. Tonite,4:34,1999-10-23,28,15.0
2180,2346,2000,"Houston, Whitney",I Learned From The B...,4:18,2000-02-19,8,36.0
4704,6279,2000,SheDaisy,I Will.. But,3:40,2000-07-15,20,87.0
1254,1288,2000,Avant,My First Love,4:28,2000-11-04,5,39.0
4013,4954,2000,"McEntire, Reba",I'll Be,4:23,2000-05-13,16,84.0
3307,3825,2000,Avant,Separated,4:13,2000-04-29,13,27.0
3541,4181,2000,Common,The Light,3:55,2000-08-05,14,82.0
2426,2650,2000,"Griggs, Andy",She's More,3:19,2000-03-11,9,51.0
3191,3662,2000,Lil' Zane,Callin' Me,3:43,2000-07-29,12,84.0
4852,6987,2000,"Aguilera, Christina",What A Girl Wants,3:18,1999-11-27,23,39.0
3336,3870,2000,D'Angelo,Untitled (How Does I...,7:10,2000-01-22,13,51.0
4141,5169,2000,"Evans, Sara",Born To Fly,5:36,2000-10-21,17,58.0
4086,5075,2000,3 Doors Down,Loser,4:24,2000-10-21,17,75.0
3351,3890,2000,Drama,"Left, Right, Left",3:37,2000-02-12,13,96.0
4307,5472,2000,"Dixie Chicks, The",Without You,3:32,2000-10-07,18,43.0
614,619,2000,Vitamin C,Graduation (Friends ...,4:23,2000-04-15,2,64.0
3309,3827,2000,"Backstreet Boys, The",Shape Of My Heart,3:49,2000-10-14,13,29.0
3957,4846,2000,"Elliott, Missy ""Misdemeanor""",Hot Boyz,3:51,1999-11-27,16,12.0
4863,7050,2000,Destiny's Child,Say My Name,4:31,1999-12-25,23,10.0
58,58,2000,Clark Family Experience,Meanwhile Back At Th...,2:56,2000-11-18,1,87.0
1765,1854,2000,Sonique,It Feels So Good,3:48,2000-01-22,6,17.0
2105,2253,2000,"Black, Clint",Been There,5:28,2000-02-19,8,47.0
2117,2268,2000,"Cagle, Chris",My Love Goes On And ...,3:02,2000-10-21,8,76.0
2587,2847,2000,"Wright, Chely",It Was,3:51,2000-03-04,9,85.0
2580,2839,2000,Vitamin C,The Itch,3:30,2000-12-02,9,100.0
745,755,2000,"Hill, Faith",Breathe,4:04,1999-11-06,3,62.0
875,887,2000,Savage Garden,Crash And Burn,4:41,2000-04-08,3,51.0
4985,7944,2000,"Anthony, Marc",You Sang To Me,3:50,2000-02-26,26,25.0
1394,1442,2000,Lil' Mo,Ta Da,4:17,2000-08-12,5,100.0
4288,5431,2000,"Braxton, Toni",Just Be A Man About ...,4:10,2000-07-29,18,84.0
1127,1155,2000,"McKnight, Brian",Stay Or Let It Go,4:32,2000-02-26,4,78.0
2594,2860,2000,Aaliyah,I Don't Wanna,4:15,2000-01-29,10,36.0
1935,2048,2000,Jay-Z,Hey Papi,3:40,2000-08-12,7,80.0
1789,1882,2000,Usher,Pop Ya Collar,3:36,2000-11-04,6,79.0

In [7]:
import datetime

da = []
for i in range(0,5307):
    j = df['date.entered'][i]
    w = int(df['week'][i])
    w = (w -1) * 7
    t = datetime.datetime.strptime(j, "%Y-%m-%d")
    t = t + datetime.timedelta(days=w)
    t = t.strftime('%Y-%m-%d')
    da.append(t)
da

['2000-02-26',
 '2000-09-02',
 '2000-04-08',
 '2000-10-21',
 '2000-04-15',
 '2000-08-19',
 '2000-07-08',
 '2000-01-29',
 '2000-03-18',
 '2000-08-26',
 '2000-04-29',
 '2000-08-05',
 '2000-04-15',
 '1999-11-27',
 '2000-04-08',
 '2000-01-22',
 '1999-07-17',
 '2000-04-01',
 '2000-09-16',
 '2000-02-26',
 '2000-11-04',
 '2000-04-29',
 '2000-04-29',
 '2000-10-14',
 '2000-01-01',
 '2000-05-27',
 '2000-08-19',
 '2000-07-22',
 '2000-09-09',
 '2000-10-21',
 '2000-05-20',
 '2000-01-29',
 '2000-04-22',
 '2000-03-04',
 '2000-02-19',
 '1999-10-23',
 '1999-11-13',
 '2000-04-15',
 '1999-12-04',
 '2000-03-18',
 '2000-08-12',
 '2000-03-18',
 '2000-07-29',
 '2000-12-02',
 '2000-01-01',
 '2000-04-08',
 '2000-06-10',
 '2000-02-19',
 '2000-01-29',
 '2000-10-21',
 '2000-10-14',
 '2000-06-24',
 '1999-12-11',
 '2000-08-26',
 '2000-06-24',
 '2000-09-30',
 '2000-10-21',
 '2000-04-01',
 '2000-11-18',
 '2000-12-16',
 '2000-08-05',
 '1999-11-06',
 '1999-09-11',
 '2000-05-13',
 '2000-09-23',
 '1999-12-11',
 '2000-01-22',
 '2000-02-26',
 '2000-07-01',
 '2000-01-15',
 '2000-02-26',
 '2000-06-03',
 '2000-03-25',
 '2000-12-23',
 '2000-09-23',
 '2000-05-13',
 '1999-12-25',
 '2000-08-12',
 '2000-01-01',
 '1999-11-13',
 '2000-06-24',
 '1999-11-27',
 '2000-03-18',
 '2000-10-07',
 '2000-01-22',
 '2000-05-27',
 '2000-02-12',
 '2000-09-30',
 '2000-01-08',
 '2000-07-01',
 '1999-12-11',
 '1999-11-27',
 '2000-11-04',
 '2000-05-06',
 '2000-08-26',
 '2000-06-17',
 '2000-06-10',
 '2000-10-21',
 '2000-07-15',
 '2000-01-08',
 '2000-07-08',
 '2000-06-10',
 '1999-11-13',
 '1999-11-27',
 '1999-10-16',
 '2000-10-28',
 '2000-11-11',
 '2000-08-05',
 '2000-09-02',
 '2000-06-17',
 '1999-12-11',
 '2000-01-08',
 '2000-04-22',
 '2000-02-19',
 '2000-03-11',
 '1999-12-18',
 '2000-04-22',
 '1999-11-27',
 '2000-04-29',
 '2000-06-24',
 '2000-03-18',
 '1999-11-06',
 '2000-08-12',
 '2000-02-19',
 '2000-03-25',
 '2000-02-19',
 '2000-06-17',
 '2000-02-19',
 '1999-09-04',
 '2000-06-17',
 '1999-10-09',
 '1999-12-04',
 '2000-06-10',
 '2000-04-01',
 '1999-12-04',
 '1999-12-25',
 '2000-09-16',
 '2000-06-24',
 '1999-11-13',
 '2000-11-04',
 '1999-12-11',
 '2000-05-06',
 '2000-06-17',
 '2000-02-26',
 '2000-04-22',
 '2000-01-15',
 '2000-08-12',
 '2000-10-28',
 '2000-10-07',
 '2000-01-01',
 '2000-08-05',
 '2000-04-22',
 '2000-04-22',
 '1999-10-23',
 '2000-02-05',
 '2000-08-05',
 '2000-08-05',
 '2000-01-29',
 '1999-12-04',
 '1999-12-25',
 '2000-02-19',
 '2000-03-25',
 '2000-03-04',
 '2000-04-15',
 '2000-08-05',
 '2000-08-12',
 '2000-03-04',
 '2000-01-29',
 '2000-08-19',
 '2000-03-18',
 '2000-08-19',
 '1999-12-04',
 '2000-11-25',
 '2000-07-15',
 '2000-08-12',
 '2000-07-29',
 '1999-12-04',
 '1999-12-04',
 '2000-11-11',
 '1999-06-05',
 '1999-12-18',
 '2000-06-10',
 '2000-02-19',
 '2000-09-16',
 '2000-03-18',
 '2000-05-20',
 '2000-09-30',
 '1999-11-20',
 '2000-04-01',
 '2000-07-08',
 '2000-02-19',
 '2000-08-12',
 '2000-03-11',
 '1999-11-20',
 '2000-10-07',
 '2000-03-25',
 '2000-11-18',
 '2000-02-05',
 '2000-09-09',
 '2000-05-13',
 '1999-10-30',
 '1999-11-27',
 '2000-10-21',
 '2000-05-13',
 '2000-02-26',
 '2000-01-29',
 '2000-06-24',
 '2000-05-13',
 '2000-02-12',
 '2000-03-04',
 '2000-09-09',
 '2000-10-28',
 '2000-06-17',
 '2000-09-09',
 '2000-10-14',
 '2000-08-19',
 '2000-04-15',
 '2000-08-12',
 '2000-01-29',
 '2000-05-06',
 '2000-09-30',
 '2000-03-25',
 '2000-04-29',
 '2000-05-27',
 '2000-05-06',
 '2000-12-02',
 '2000-07-01',
 '2000-06-03',
 '2000-11-25',
 '2000-05-13',
 '2000-10-14',
 '2000-07-29',
 '2000-05-13',
 '2000-08-12',
 '2000-03-04',
 '2000-07-15',
 '2000-05-13',
 '2000-09-23',
 '2000-09-16',
 '2000-02-12',
 '2000-01-22',
 '1999-12-25',
 '2000-05-06',
 '2000-03-18',
 '2000-07-29',
 '2000-02-12',
 '1999-10-16',
 '2000-09-09',
 '2000-05-27',
 '2000-03-11',
 '2000-07-01',
 '2000-01-29',
 '2000-02-12',
 '2000-04-08',
 '1999-10-23',
 '1999-12-25',
 '2000-07-15',
 '2000-02-05',
 '2000-11-11',
 '2000-09-09',
 '2000-07-01',
 '2000-04-01',
 '1999-11-20',
 '2000-06-24',
 '2000-01-29',
 '2000-07-15',
 '1999-10-30',
 '2000-02-12',
 '2000-04-08',
 '2000-01-22',
 '2000-07-08',
 '2000-01-29',
 '2000-08-12',
 '2000-04-22',
 '2000-03-04',
 '2000-06-10',
 '2000-05-13',
 '2000-07-08',
 '1999-12-25',
 '2000-08-26',
 '2000-01-29',
 '2000-01-15',
 '2000-02-12',
 '2000-03-25',
 '2000-09-16',
 '2000-09-02',
 '2000-01-22',
 '2000-11-25',
 '2000-03-25',
 '2000-09-23',
 '2000-08-26',
 '1999-10-09',
 '2000-05-20',
 '2000-09-09',
 '2000-08-19',
 '2000-12-30',
 '2000-07-15',
 '2000-11-04',
 '2000-03-04',
 '2000-09-30',
 '2000-01-22',
 '2000-08-26',
 '2000-04-15',
 '2000-12-02',
 '1999-12-04',
 '2000-04-15',
 '2000-10-28',
 '2000-04-01',
 '1999-11-20',
 '2000-01-15',
 '2000-06-17',
 '2000-03-04',
 '2000-04-29',
 '2000-04-01',
 '2000-03-18',
 '2000-09-02',
 '2000-04-29',
 '2000-03-04',
 '2000-09-09',
 '2000-04-15',
 '2000-10-28',
 '2000-04-22',
 '2000-08-26',
 '2000-07-15',
 '2000-02-05',
 '2000-03-25',
 '2000-09-02',
 '2000-05-06',
 '2000-08-12',
 '2000-04-22',
 '1999-12-04',
 '2000-04-15',
 '2000-01-29',
 '1999-07-24',
 '2000-09-23',
 '2000-03-04',
 '2000-11-11',
 '2000-05-06',
 '2000-05-06',
 '2000-10-21',
 '2000-01-08',
 '2000-06-03',
 '2000-08-26',
 '2000-07-29',
 '2000-09-16',
 '2000-10-28',
 '2000-05-27',
 '2000-02-05',
 '2000-04-29',
 '2000-03-11',
 '2000-02-26',
 '1999-10-30',
 '1999-11-20',
 '2000-04-22',
 '1999-12-11',
 '2000-03-25',
 '2000-08-19',
 '2000-03-25',
 '2000-08-05',
 '2000-12-09',
 '2000-01-08',
 '2000-04-15',
 '2000-06-17',
 '2000-02-26',
 '2000-02-05',
 '2000-10-28',
 '2000-10-21',
 '2000-07-01',
 '1999-12-18',
 '2000-09-02',
 '2000-07-01',
 '2000-10-07',
 '2000-10-28',
 '2000-04-08',
 '2000-11-25',
 '2000-12-23',
 '2000-08-12',
 '1999-11-13',
 '1999-09-18',
 '2000-05-20',
 '2000-09-30',
 '1999-12-18',
 '2000-01-29',
 '2000-03-04',
 '2000-07-08',
 '2000-01-22',
 '2000-03-04',
 '2000-06-10',
 '2000-04-01',
 '2000-12-30',
 '2000-09-30',
 '2000-05-20',
 '2000-01-01',
 '2000-08-19',
 '2000-01-08',
 '1999-11-20',
 '2000-07-01',
 '1999-12-04',
 '2000-03-25',
 '2000-10-14',
 '2000-01-29',
 '2000-06-03',
 '2000-02-19',
 '2000-10-07',
 '2000-01-15',
 '2000-07-08',
 '1999-12-18',
 '1999-12-04',
 '2000-11-11',
 '2000-05-13',
 '2000-09-02',
 '2000-06-24',
 '2000-10-28',
 '2000-07-22',
 '2000-01-15',
 '2000-07-15',
 '2000-06-17',
 '1999-11-20',
 '1999-12-04',
 '1999-10-23',
 '2000-11-18',
 '2000-09-09',
 '2000-06-24',
 '1999-12-18',
 '2000-01-15',
 '2000-04-29',
 '2000-02-26',
 '2000-03-18',
 '1999-12-25',
 '2000-04-29',
 '1999-12-04',
 '2000-05-06',
 '2000-07-01',
 '2000-03-25',
 '1999-11-13',
 '2000-08-19',
 '2000-02-26',
 '2000-04-01',
 '2000-02-26',
 '2000-06-24',
 '2000-02-26',
 '1999-09-11',
 '2000-06-24',
 '1999-10-16',
 '1999-12-11',
 '2000-06-17',
 '2000-04-08',
 '1999-12-11',
 '2000-01-01',
 '2000-09-23',
 '2000-07-01',
 '1999-11-20',
 '2000-11-11',
 '1999-12-18',
 '2000-05-13',
 '2000-06-24',
 '2000-03-04',
 '2000-04-29',
 '2000-01-22',
 '2000-08-19',
 '2000-11-04',
 '2000-10-14',
 '2000-01-08',
 '2000-08-12',
 '2000-04-29',
 '2000-04-29',
 '1999-10-30',
 '2000-02-12',
 '2000-08-12',
 '2000-08-12',
 '2000-02-05',
 '1999-12-11',
 '2000-01-01',
 '2000-02-26',
 '2000-04-01',
 '2000-03-11',
 '2000-04-22',
 '2000-08-12',
 '2000-08-19',
 '2000-03-11',
 '2000-02-05',
 '2000-08-26',
 '2000-03-25',
 '2000-08-26',
 '1999-12-11',
 '2000-12-02',
 '2000-07-22',
 '2000-08-19',
 '2000-08-05',
 '1999-12-11',
 '1999-12-11',
 '2000-11-18',
 '1999-06-12',
 '1999-12-25',
 '2000-06-17',
 '2000-02-26',
 '2000-09-23',
 '2000-03-25',
 '2000-05-27',
 '2000-10-07',
 '1999-11-27',
 '2000-04-08',
 '2000-07-15',
 '2000-02-26',
 '2000-08-19',
 '2000-03-18',
 '1999-11-27',
 '2000-10-14',
 '2000-04-01',
 '2000-02-12',
 '2000-09-16',
 '2000-05-20',
 '1999-11-06',
 '1999-12-04',
 '2000-10-28',
 '2000-05-20',
 '2000-03-04',
 '2000-02-05',
 '2000-07-01',
 '2000-05-20',
 '2000-02-19',
 '2000-03-11',
 '2000-09-16',
 '2000-11-04',
 '2000-06-24',
 '2000-09-16',
 '2000-10-21',
 '2000-08-26',
 '2000-04-22',
 '2000-08-19',
 '2000-02-05',
 '2000-05-13',
 '2000-10-07',
 '2000-04-01',
 '2000-05-06',
 '2000-06-03',
 '2000-05-13',
 '2000-12-09',
 '2000-07-08',
 '2000-06-10',
 '2000-12-02',
 '2000-05-20',
 '2000-10-21',
 '2000-08-05',
 '2000-05-20',
 '2000-08-19',
 '2000-03-11',
 '2000-07-22',
 '2000-05-20',
 '2000-09-30',
 '2000-09-23',
 '2000-02-19',
 '2000-01-29',
 '2000-01-01',
 '2000-05-13',
 '2000-03-25',
 '2000-08-05',
 '2000-02-19',
 '1999-10-23',
 '2000-09-16',
 '2000-06-03',
 '2000-03-18',
 '2000-07-08',
 '2000-02-05',
 '2000-02-19',
 '2000-04-15',
 '1999-10-30',
 '2000-01-01',
 '2000-07-22',
 '2000-02-12',
 '2000-11-18',
 '2000-09-16',
 '2000-07-08',
 '2000-04-08',
 '1999-11-27',
 '2000-07-01',
 '2000-02-05',
 '2000-07-22',
 '1999-11-06',
 '2000-02-19',
 '2000-04-15',
 '2000-01-29',
 '2000-07-15',
 '2000-02-05',
 '2000-08-19',
 '2000-04-29',
 '2000-03-11',
 '2000-06-17',
 '2000-05-20',
 '2000-07-15',
 '2000-01-01',
 '2000-09-02',
 '2000-02-05',
 '2000-01-22',
 '2000-02-19',
 '2000-04-01',
 '2000-09-23',
 '2000-09-09',
 '2000-01-29',
 '2000-12-02',
 '2000-04-01',
 '2000-09-30',
 '2000-09-02',
 '1999-10-16',
 '2000-05-27',
 '2000-09-16',
 '2000-08-26',
 '2001-01-06',
 '2000-07-22',
 '2000-11-11',
 '2000-03-11',
 '2000-10-07',
 '2000-01-29',
 '2000-09-02',
 '2000-04-22',
 '2000-12-09',
 '1999-12-11',
 '2000-04-22',
 '2000-11-04',
 '2000-04-08',
 '1999-11-27',
 '2000-01-22',
 '2000-06-24',
 '2000-03-11',
 '2000-05-06',
 '2000-04-08',
 '2000-03-25',
 '2000-09-09',
 '2000-05-06',
 '2000-03-11',
 '2000-09-16',
 '2000-04-22',
 '2000-11-04',
 '2000-04-29',
 '2000-09-02',
 '2000-07-22',
 '2000-02-12',
 '2000-04-01',
 '2000-09-09',
 '2000-05-13',
 '2000-08-19',
 '2000-04-29',
 '1999-12-11',
 '2000-04-22',
 '2000-02-05',
 '1999-07-31',
 '2000-09-30',
 '2000-03-11',
 '2000-11-18',
 '2000-05-13',
 '2000-05-13',
 '2000-10-28',
 '2000-01-15',
 '2000-06-10',
 '2000-09-02',
 '2000-08-05',
 '2000-09-23',
 '2000-11-04',
 '2000-06-03',
 '2000-02-12',
 '2000-05-06',
 '2000-03-18',
 '2000-03-04',
 '1999-11-06',
 '1999-11-27',
 '2000-04-29',
 '1999-12-18',
 '2000-04-01',
 '2000-08-26',
 '2000-04-01',
 '2000-08-12',
 '2000-12-16',
 '2000-01-15',
 '2000-04-22',
 '2000-06-24',
 '2000-03-04',
 '2000-02-12',
 '2000-11-04',
 '2000-10-28',
 '2000-07-08',
 '1999-12-25',
 '2000-09-09',
 '2000-07-08',
 '2000-10-14',
 '2000-11-04',
 '2000-04-15',
 '2000-12-02',
 '2000-12-30',
 '2000-08-19',
 '1999-11-20',
 '1999-09-25',
 '2000-05-27',
 '2000-10-07',
 '1999-12-25',
 '2000-02-05',
 '2000-03-11',
 '2000-07-15',
 '2000-01-29',
 '2000-03-11',
 '2000-06-17',
 '2000-04-08',
 '2001-01-06',
 '2000-10-07',
 '2000-05-27',
 '2000-01-08',
 '2000-08-26',
 '2000-01-15',
 '1999-11-27',
 '2000-07-08',
 '1999-12-11',
 '2000-04-01',
 '2000-10-21',
 '2000-02-05',
 '2000-06-10',
 '2000-02-26',
 '2000-10-14',
 '2000-01-22',
 '1999-12-25',
 '1999-12-11',
 '2000-11-18',
 '2000-05-20',
 '2000-09-09',
 '2000-07-01',
 '2000-11-04',
 '2000-07-29',
 '2000-01-22',
 '2000-07-22',
 '2000-06-24',
 '1999-11-27',
 '1999-12-11',
 '1999-10-30',
 '2000-11-25',
 '2000-09-16',
 '2000-07-01',
 '1999-12-25',
 '2000-01-22',
 '2000-05-06',
 '2000-03-04',
 '2000-03-25',
 '2000-01-01',
 '2000-05-06',
 '1999-12-11',
 '2000-05-13',
 '2000-07-08',
 '2000-04-01',
 '1999-11-20',
 '2000-08-26',
 '2000-03-04',
 '2000-04-08',
 '2000-03-04',
 '2000-07-01',
 '2000-03-04',
 '1999-09-18',
 '2000-07-01',
 '1999-10-23',
 '1999-12-18',
 '2000-06-24',
 '2000-04-15',
 '1999-12-18',
 '2000-01-08',
 '2000-09-30',
 '2000-07-08',
 '1999-11-27',
 '2000-11-18',
 '1999-12-25',
 '2000-05-20',
 '2000-07-01',
 '2000-03-11',
 '2000-05-06',
 '2000-01-29',
 '2000-08-26',
 '2000-11-11',
 '2000-10-21',
 '2000-01-15',
 '2000-08-19',
 '2000-05-06',
 '2000-05-06',
 '1999-11-06',
 '2000-02-19',
 '2000-08-19',
 '2000-08-19',
 '2000-02-12',
 '1999-12-18',
 '2000-01-08',
 '2000-03-04',
 '2000-04-08',
 '2000-03-18',
 '2000-04-29',
 '2000-08-19',
 '2000-03-18',
 '2000-02-12',
 '2000-09-02',
 '2000-04-01',
 '2000-09-02',
 '1999-12-18',
 '2000-12-09',
 '2000-07-29',
 '2000-08-26',
 '2000-08-12',
 '1999-12-18',
 '1999-12-18',
 '2000-11-25',
 '1999-06-19',
 '2000-01-01',
 '2000-06-24',
 '2000-03-04',
 '2000-09-30',
 '2000-04-01',
 '2000-06-03',
 '2000-10-14',
 '1999-12-04',
 '2000-04-15',
 '2000-07-22',
 '2000-03-04',
 '2000-08-26',
 '2000-03-25',
 '1999-12-04',
 '2000-10-21',
 '2000-04-08',
 '2000-02-19',
 '2000-09-23',
 '2000-05-27',
 '1999-11-13',
 '1999-12-11',
 '2000-11-04',
 '2000-05-27',
 '2000-03-11',
 '2000-02-12',
 '2000-07-08',
 '2000-05-27',
 '2000-02-26',
 '2000-03-18',
 '2000-09-23',
 '2000-11-11',
 '2000-07-01',
 '2000-09-23',
 '2000-10-28',
 '2000-09-02',
 '2000-04-29',
 '2000-08-26',
 '2000-02-12',
 '2000-05-20',
 '2000-10-14',
 '2000-04-08',
 '2000-05-13',
 '2000-06-10',
 '2000-05-20',
 '2000-12-16',
 '2000-07-15',
 '2000-06-17',
 '2000-12-09',
 '2000-05-27',
 '2000-10-28',
 '2000-08-12',
 '2000-05-27',
 '2000-08-26',
 '2000-03-18',
 '2000-07-29',
 '2000-05-27',
 '2000-10-07',
 '2000-09-30',
 '2000-02-26',
 '2000-02-05',
 '2000-01-08',
 '2000-05-20',
 '2000-04-01',
 '2000-08-12',
 '2000-02-26',
 '1999-10-30',
 '2000-09-23',
 '2000-06-10',
 '2000-03-25',
 '2000-07-15',
 '2000-02-12',
 '2000-02-26',
 '2000-04-22',
 '1999-11-06',
 '2000-07-29',
 '2000-02-19',
 '2000-11-25',
 '2000-09-23',
 '2000-07-15',
 '2000-04-15',
 '1999-12-04',
 '2000-07-08',
 '2000-02-12',
 '2000-07-29',
 '1999-11-13',
 '2000-02-26',
 '2000-04-22',
 '2000-02-05',
 '2000-07-22',
 '2000-02-12',
 '2000-08-26',
 '2000-05-06',
 '2000-03-18',
 '2000-06-24',
 '2000-05-27',
 '2000-07-22',
 '2000-01-08',
 '2000-09-09',
 '2000-02-12',
 '2000-01-29',
 '2000-02-26',
 '2000-04-08',
 '2000-09-30',
 '2000-09-16',
 '2000-02-05',
 '2000-12-09',
 '2000-04-08',
 '2000-10-07',
 '2000-09-09',
 '1999-10-23',
 '2000-06-03',
 '2000-09-23',
 '2000-09-02',
 '2000-07-29',
 '2000-11-18',
 '2000-03-18',
 '2000-10-14',
 '2000-02-05',
 '2000-09-09',
 '2000-04-29',
 '2000-12-16',
 '1999-12-18',
 '2000-04-29',
 '2000-11-11',
 '2000-04-15',
 '1999-12-04',
 '2000-01-29',
 '2000-07-01',
 '2000-03-18',
 '2000-05-13',
 '2000-04-15',
 '2000-04-01',
 '2000-05-13',
 '2000-03-18',
 '2000-04-29',
 '2000-11-11',
 '2000-05-06',
 '2000-09-09',
 '2000-07-29',
 '2000-02-19',
 '2000-04-08',
 '2000-09-16',
 '2000-05-20',
 '2000-08-26',
 '2000-05-06',
 '1999-12-18',
 '2000-04-29',
 '2000-02-12',
 '1999-08-07',
 '2000-04-22',
 '2000-10-07',
 '2000-03-18',
 '2000-11-25',
 '2000-05-20',
 '2000-05-20',
 '2000-11-04',
 '2000-01-22',
 '2000-06-17',
 '2000-09-09',
 '2000-08-12',
 '2000-09-30',
 '2000-11-11',
 '2000-06-10',
 '2000-05-13',
 '2000-03-25',
 '2000-03-11',
 '1999-11-13',
 '1999-12-04',
 '2000-05-06',
 '1999-12-25',
 '2000-04-08',
 '2000-09-02',
 '2000-04-08',
 '2000-08-19',
 '2000-04-29',
 '2000-07-01',
 '2000-03-11',
 '2000-02-19',
 '2000-11-11',
 '2000-11-04',
 '2000-07-15',
 '2000-01-01',
 '2000-09-16',
 '2000-07-15',
 '2000-10-21',
 '2000-11-11',
 '2000-04-22',
 '2000-12-09',
 '2001-01-06',
 '2000-08-26',
 '1999-11-27',
 '1999-10-02',
 '2000-06-03',
 '2000-10-14',
 '2000-01-01',
 '2000-02-12',
 '2000-03-18',
 ...]

In [8]:
da[393]

'2000-08-19'

In [9]:
df['date.entered'] = da
df = df.rename(columns={'date.entered': 'date'})
df

,index,year,artist,track,time,date,week,rank
0,0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
1,1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,1,91.0
2,2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,1,81.0
3,3,2000,3 Doors Down,Loser,4:24,2000-10-21,1,76.0
4,4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,1,57.0
...,...,...,...,...,...,...,...,...
5302,19716,2000,Creed,Higher,5:16,2000-11-18,63,50.0
5303,19833,2000,Lonestar,Amazed,4:25,2000-08-12,63,45.0
5304,20033,2000,Creed,Higher,5:16,2000-11-25,64,50.0
5305,20150,2000,Lonestar,Amazed,4:25,2000-08-19,64,50.0
5306,20350,2000,Creed,Higher,5:16,2000-12-02,65,49.0

In [11]:
df['date'][393]

'2000-08-19'

In [17]:
df = df.sort_values(by=['artist','date'])
df

,index,year,artist,track,time,date,week,rank
0,0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
317,317,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-04,2,82.0
629,634,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-11,3,72.0
936,951,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-18,4,77.0
1236,1268,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-25,5,87.0
...,...,...,...,...,...,...,...,...
5178,11094,2000,matchbox twenty,Bent,4:12,2000-12-23,35,33.0
5187,11411,2000,matchbox twenty,Bent,4:12,2000-12-30,36,37.0
5196,11728,2000,matchbox twenty,Bent,4:12,2001-01-06,37,38.0
5204,12045,2000,matchbox twenty,Bent,4:12,2001-01-13,38,38.0
5212,12362,2000,matchbox twenty,Bent,4:12,2001-01-20,39,48.0

In [18]:
df.head(50)

,index,year,artist,track,time,date,week,rank
0,0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,1,87.0
317,317,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-04,2,82.0
629,634,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-11,3,72.0
936,951,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-18,4,77.0
1236,1268,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-03-25,5,87.0
1528,1585,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-04-01,6,94.0
1808,1902,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-04-08,7,99.0
1,1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,1,91.0
318,318,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-09,2,87.0
630,635,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-16,3,92.0
2,2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,1,81.0
319,319,2000,3 Doors Down,Kryptonite,3:53,2000-04-15,2,70.0
631,636,2000,3 Doors Down,Kryptonite,3:53,2000-04-22,3,68.0
937,953,2000,3 Doors Down,Kryptonite,3:53,2000-04-29,4,67.0
1237,1270,2000,3 Doors Down,Kryptonite,3:53,2000-05-06,5,66.0
1529,1587,2000,3 Doors Down,Kryptonite,3:53,2000-05-13,6,57.0
1809,1904,2000,3 Doors Down,Kryptonite,3:53,2000-05-20,7,54.0
2077,2221,2000,3 Doors Down,Kryptonite,3:53,2000-05-27,8,53.0
2337,2538,2000,3 Doors Down,Kryptonite,3:53,2000-06-03,9,51.0
2590,2855,2000,3 Doors Down,Kryptonite,3:53,2000-06-10,10,51.0
2834,3172,2000,3 Doors Down,Kryptonite,3:53,2000-06-17,11,51.0
3070,3489,2000,3 Doors Down,Kryptonite,3:53,2000-06-24,12,51.0
3292,3806,2000,3 Doors Down,Kryptonite,3:53,2000-07-01,13,47.0
3502,4123,2000,3 Doors Down,Kryptonite,3:53,2000-07-08,14,44.0
3706,4440,2000,3 Doors Down,Kryptonite,3:53,2000-07-15,15,38.0
3903,4757,2000,3 Doors Down,Kryptonite,3:53,2000-07-22,16,28.0
4085,5074,2000,3 Doors Down,Kryptonite,3:53,2000-07-29,17,22.0
4262,5391,2000,3 Doors Down,Kryptonite,3:53,2000-08-05,18,18.0
4428,5708,2000,3 Doors Down,Kryptonite,3:53,2000-08-12,19,18.0
4584,6025,2000,3 Doors Down,Kryptonite,3:53,2000-08-19,20,14.0
4730,6342,2000,3 Doors Down,Kryptonite,3:53,2000-08-26,21,12.0
4795,6659,2000,3 Doors Down,Kryptonite,3:53,2000-09-02,22,7.0
4850,6976,2000,3 Doors Down,Kryptonite,3:53,2000-09-09,23,6.0
4898,7293,2000,3 Doors Down,Kryptonite,3:53,2000-09-16,24,6.0
4944,7610,2000,3 Doors Down,Kryptonite,3:53,2000-09-23,25,6.0
4982,7927,2000,3 Doors Down,Kryptonite,3:53,2000-09-30,26,5.0
5018,8244,2000,3 Doors Down,Kryptonite,3:53,2000-10-07,27,5.0
5047,8561,2000,3 Doors Down,Kryptonite,3:53,2000-10-14,28,4.0
5071,8878,2000,3 Doors Down,Kryptonite,3:53,2000-10-21,29,4.0
3,3,2000,3 Doors Down,Loser,4:24,2000-10-21,1,76.0
5091,9195,2000,3 Doors Down,Kryptonite,3:53,2000-10-28,30,4.0
320,320,2000,3 Doors Down,Loser,4:24,2000-10-28,2,76.0
5111,9512,2000,3 Doors Down,Kryptonite,3:53,2000-11-04,31,4.0
632,637,2000,3 Doors Down,Loser,4:24,2000-11-04,3,72.0
5130,9829,2000,3 Doors Down,Kryptonite,3:53,2000-11-11,32,3.0
938,954,2000,3 Doors Down,Loser,4:24,2000-11-11,4,69.0
5148,10146,2000,3 Doors Down,Kryptonite,3:53,2000-11-18,33,3.0
1238,1271,2000,3 Doors Down,Loser,4:24,2000-11-18,5,67.0
1530,1588,2000,3 Doors Down,Loser,4:24,2000-11-25,6,65.0
5160,10463,2000,3 Doors Down,Kryptonite,3:53,2000-11-25,34,3.0

In [19]:
df.to_excel(r'billboard_.xlsx')